### ISSUE TITLE
A couple great features to add

### ISSUE THREAD

**Issue by josuebrunel** [MaxHalford/Directory-Architecture#1]
Hi @MaxHalford ,
Good job  ( :+1: )on your project. Just a couple suggestions 
1. You could have used **[argparse](https://docs.python.org/3/howto/argparse.html)**, or better **[docopt](https://github.com/docopt/docopt)**
2. Then allow user to define **_extension or specific file or folder**_ to ignore 

``` shell
probe --ignore-ext pyc my_folder 
probe --depth 3 my_folder
```

A lil bit like the **tree** command but **way better** :wink:

Just a couple thoughts. Have fun buddy

**Comment by MaxHalford** [comment]
Many thanks.

**Comment by josuebrunel** [comment]
De rien :smile:. En passant super tes projets et ton blog.

**Comment by MaxHalford** [comment]
C'est super gentil merci, je vais intégrer tes solutions sous peu :)
